### ISSUE TITLE
Unable to recreate development environment for StratVis

### ISSUE THREAD

**Issue by sorghumking** [demjanp/StratVis#1]
Hello, I'm trying to prepare a development environment to run StratVis locally, but thus far I've been unsuccessful.  In particular, I'm unsure what the `deposit` module refers to.  It appears to be [invenio-deposit](https://github.com/inveniosoftware/invenio-deposit), is that correct?  Due to versioning conflicts, I've been unable to install it through `pip`.

Could you provide a `requirements.txt` file or other resources necessary to recreate a working development environment?

**Comment by demjanp** [comment]
Hi, thanks for your interest in StratVis! It's still pretty much work in progress and thus missing documentation and installation instructions, but you should be able to run it. The required module is this [deposit](https://github.com/demjanp/deposit). Just download the source and copy it in a folder named "deposit" in the StratVis folder (not very elegant, I know :))

**Comment by sorghumking** [comment]
I tried your deposit instructions, now I get the following error:

```
(ve_py3) lcdev StratVis/ $ python stratvis.py 
Traceback (most recent call last):
  File "stratvis.py", line 1, in <module>
    from lib.StratVisMain import (StratVisMain)
  File "/Users/lcdev/proj/corewall/StratVis/lib/StratVisMain.py", line 1, in <module>
    from lib.View import (View)
  File "/Users/lcdev/proj/corewall/StratVis/lib/View.py", line 4, in <module>
    from deposit.gui import (DView, DMenu, DToolbar, Dialogs, GraphView, Separator)
  File "/Users/lcdev/proj/corewall/StratVis/ve_py3/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'deposit.gui'
```

Are you running against Python 3?  What other dependencies need to be installed?

**Comment by demjanp** [comment]
So it's a bit more complicated. The current StratVis version requires an experimental version of deposit, which is currently not available on GitHub. I'm attaching it here, if you like to try it:
[deposit.zip](https://github.com/demjanp/StratVis/files/8709568/deposit.zip)
